# Generated by Django 3.1.2 on 2021-12-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdversarialTool', '0002_attacks_attacktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacks',
            name='newClassification',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attacks',
            name='originalClassification',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attacks',
            name='attackType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
